version: '2'
services:
    nginx:
        image: nginx:1.11.1
        ports:
            - "80:80"
        depends_on:
            - tomcat
        volumes:
            - ./app:/mnt/app
            - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/config/sites-enabled:/etc/nginx/sites-enabled
            - ./data/nginx/logs/:/var/log/nginx/
    tomcat:
        image: tomcat:8.0
        environment:
            CATALINA_BASE: "/usr/local/tomcat"
            CATALINA_HOME: "/usr/local/tomcat"
            CATALINA_TMPDIR: "/usr/local/tomcat/temp"
            JRE_HOME: "/usr"
            CLASSPATH: "/usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar"
        volumes:
            - ./services/tomcat/bin/startup.sh:/usr/local/tomcat/bin/startup.sh
            - ./services/tomcat/config/server.xml:/usr/local/tomcat/conf/server.xml
            - ./services/tomcat/config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
            - ./services/tomcat/config/logging.properties:/usr/local/tomcat/logging.properties
            - ./data/tomcat/logs/:/usr/local/tomcat/logs/
            - ./app/java-webapp/:/usr/local/tomcat/webapps/
    mysql:
        image: mysql:5.7.22
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "app"
            MYSQL_PASSWORD: "secret"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./services/mysql/config/my.cnf:/etc/mysql/my.cnf
